name: ci
"on":
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: pnpm/action-setup
        with:
          version: 8
      - uses: actions/setup-node
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm i
      - run: pnpm lint-check
      - run: pnpm tsc
      - run: pnpm build
